version: "3"

services:
    client:
        image: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./src:/usr/share/nginx/html
            - ./letsencrypt:/etc/letsencrypt
        build: ./nginx
