version: "3.4"

services:
    nginx:
        build:
            context: ./nginx
            args:
              - CERTBOT_EMAIL=contacto@ticsalud.cl #replace with your own email
              - DOMAIN_LIST=ticsalud.cl, www.ticsalud.cl #replace with your own

        ports:
            - 80:80
            - 443:443
        volumes:
            - ./src:/usr/share/nginx/html
            - letsencrypt:/etc/letsencrypt
        restart: always
