version: "3"

services:
    client:
        image: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./src:/usr/share/nginx/html/
            - ./letsencrypt/live/www.ticsalud.cl:/etc/letsencrypt/live/www.ticsalud.cl/
            - ./letsencrypt:/etc/letsencrypt/
        build: ./nginx
