version: "3.4"

services:
    nginx:
        build:
            context: ./nginx

        ports:
            - 80:80
            - 443:443
        volumes:
            - ./src:/usr/share/nginx/html
            - ./letsencrypt:/etc/letsencrypt
        restart: always

